- main
  vmImage: Default

variables:
  buildConfiguration: 'Release'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

pool: MyAgentPool
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
steps:
- bash: echo hello world