trigger:
  - main

pool:
  name: Azure Pipelines

steps:
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(1)(b28faa7d-94d9-4bed-be7b-b816bdb6e869)'
    command: 'build'

- bash: echo hello world