trigger:
  - main

pool:
  name: Default

steps:
- checkout: self
  fetchDepth: 1

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(b28faa7d-94d9-4bed-be7b-b816bdb6e869)'
    command: 'build'

- bash: echo hello world
